minio:
  address: localhost
  port: 9000
  ssl: false
  accesskey: akey
  secretkey: skey
  bucket: gleaner
  region: null
implementation_network:
  orgname: iow
context:
  cache: true
  strict: true
contextmaps:
  - prefix: "https://schema.org/"
    file: "./assets/schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
  - prefix: "http://schema.org/"
    file: "./assets/schemaorg-current-http.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
objects:
  domain: us-east-1
  prefix:
    - summoned/providera
    - prov/providera
    - org
endpoints:
  - server: blazegraph
    type: sparql
    url: http://coreos.lan:9090/blazegraph/namespace/iow/sparql
    method: GET
    contentType: text/x-nquads
    authenticate: false
    username: admin
    password: jfpwd
  - server: blazegraph
    type: update
    url: http://coreos.lan:9090/blazegraph/namespace/iow/sparql
    method: POST
    contentType: text/x-nquads
    authenticate: false
    username: admin
    password: jfpwd
  - server: blazegraph
    type: bulk
    url: http://coreos.lan:9090/blazegraph/namespace/iow/sparql
    method: POST
    contentType: text/x-nquads
    authenticate: false
    username: admin
    password: jfpwd
  - server: graphdb
    type: sparql
    url: http://coreos.lan:7200/repositories/testing
    method: GET
    contentType: text/x-nquads
    authenticate: false
    username: admin
    password: jfpwd
  - server: graphdb
    type: update
    url: http://coreos.lan:7200/repositories/testing/statements
    method: POST
    contentType: text/x-nquads
    authenticate: false
    username: admin
    password: jfpwd
  - server: graphdb
    type: bulk
    url: http://coreos.lan:7200/repositories/testing/statements
    method: POST
    contentType: text/x-nquads
    authenticate: false
    username: admin
    password: jfpwd

